### PR TITLE
Adding a module to help configure the client

### LINKED ISSUE #10: User level documentation
Add some simple request (list Pods etc) examples to the README to help new users get started and how to authenticate etc.

### PR DESCRIPTION
**Pull request by guoshimin**
Also changed README.md to provide an example.

Fixes #10

### CODE REVIEW

**Comment by guoshimin** [comment]
ping @mbohlool

**Comment by mbohlool** [comment]
@guoshimin I don't know haskell. I can merge the PR but we need to find somebody to review these changes.

**Comment by mbohlool** [comment]
two more notes:
- I see you changed file in kubernetes/ folder. That folder is auto-generated. We prefer not to change them as much as possible (e.g. change the top level README file instead of kubernetes/README file). If the change is absolutely necessary, make sure they are added to .swagger-codegen-ignore list. The /gen repo also remove some directories before generation. check that one too
- Please squash commits to have smaller number of meaningful commits.

Thanks again.

**Comment by guoshimin** [comment]
I changed the README under kubernetes because that's the one that will be shown in Haskell's package repo, Hackage. It's the one that's most discoverable for users of Haskell. I will add it to .swagger-codegen-ignore and check directory removal. Thanks!

**Comment by mbohlool** [comment]
Thanks. To sanity check, just run the generator again (using the command in the main README) and see if your changes is being overwritten.

**Comment by mbohlool** [comment]
I am waiting for somebody with haskell knowledge to lgtm this, and then I can merge it.

**Comment by jonschoning** [comment]
lgtm

**Comment by brendandburns** [comment]
merging on LGTM from @jonschoning and @jhedev

**Pull request merged**
