### PR TITLE
Add license entries and dependency upper bounds

### PR DESCRIPTION
**Pull request by alexjg**
I'm making a start on getting this into Hackage to help with #5 . I'm assuming one of the project maintainers will want to actually push the thing to Hackage. I'm getting a bunch of failing tests but they're also failing on `master` so will look into that separately.

All I've done here is add upper counds for dependencies as per the hackage guildelines and add a bunch of license references. Do we need to do anything else?

### CODE REVIEW

**Comment by guoshimin** [comment]
The test failures are `Just Null` vs `Nothing` in roundtrip tests. I remember @jonschoning (author of the haskell module of swagger codegen) mention it at one point.

**Comment by guoshimin** [comment]
@alexjg Can you enlighten me on how you came up with these bounds? This is a question that has always puzzled me.

**Comment by jonschoning** [comment]
fyi - since `kubernetes/kubernetes.cabal` is autogenerated, those changes would be lost by default on regen

**Comment by alexjg** [comment]
@guoshimin sadly I basically guessed them by just pulling whatever the current latest on Hackage is. If there's another way of doing it I would be happy to do that. As far as I can tell though dependency resolution problems like this are hard, boring, and not going away :slightly_frowning_face: 

@jonschoning Ah, for some reason didn't realise the kubernetes.cabal was autogenerated. Shall I move this stuff to `package.yaml` as with the other subprojects?

General FYI: I'm not an expert at Haskell packaging or anything, just keen to use this project and happy to do the donkey work to get it pushed to Hackage so just let me know things that need doing.

**Comment by alexjg** [comment]
@jonschoning How exactly is `kubernetes/kubernetes.cabal` generated? There's no script in the repo that I can see so I assume by manually runing swagger-codegen?

**Comment by guoshimin** [comment]
There is some brief documentation at
https://github.com/kubernetes-client/haskell/blob/master/README.md. I'll
give you the full instructions when I get in front of a computer.

**Comment by jonschoning** [comment]
Is the intention to publish 5 packages to Hackage? How will users know they are related, or which ones to use?

**Comment by alexjg** [comment]
Good point, I had assumed multiple packages based on the existing directory layout. If we want to merge them I guess we would need to do some restructuring. Alternatively, multiple packages doesn't seem to be uncommon, e.g Servant has servant, servant-auth, servant-client etc.

**Comment by jonschoning** [comment]
I don't think they can be merged into 1, at least not the auto-gen'd package.  but users will have to know to use `kubernetes-client-helper` as the entry point somehow

**Comment by jonschoning** [comment]
Also, not sure if the root `kubernetes` name should be reserved or if it should be qualified/prefixed somehow

**Comment by guoshimin** [comment]
I was thinking we can have two packages: kubernetes-openapi that is auto generated, and all the hand-written code in another package. @jonschoning you made some change to swagger-codegen to add the ability to customize the package name, right? And we can write a README.md page for the codegen'ed package to point users to the entrypoint and configure the codegen process to not override the README.md.

@alexjg sorry this is turning into kind of a rabbit hole :p

**Comment by jonschoning** [comment]
yes, the generator can customize the base module name and the cabal package name independantly with CLI params

```
 -DbaseModule=XXX -DcabalPackage=YYY
```

**Comment by alexjg** [comment]
@guoshimin Fine by me, I'm happier to go down a rabbit hole then for no one to respond :)

How do you propose we configure the codegen process to not overwrite `README.md`?

**Comment by guoshimin** [comment]
Looks like it's already configured to not overwrite README.md here https://github.com/kubernetes-client/haskell/blob/master/kubernetes/.swagger-codegen-ignore

**Comment by alexjg** [comment]
Okay that makes sense. Would that mean consolidating `kubernetes-watch`, `kubernetes-client-helper`, and `kubeconfig` into the proposed `kubernetes` package?

**Comment by denibertovic** [comment]
What is currently missing for getting this published? I'd be happy to help if you can direct me where help is needed.

Regarding the naming I think the `amazonka` and `gogol` libraries are good examples of how to approach the split and naming. I propose we call the main package `kubernetes` which would include the bare minimum for a working setup and would at least include `kubernetes-core` and `kubernetes-client`.

**Comment by denibertovic** [comment]
@guoshimin no worries...just wondering if I can help somehow. Let me know.

**Comment by denibertovic** [comment]
@guoshimin is this PR still relevant given that #31 was merged?

**Comment by guoshimin** [comment]
yeah, the changes here need to be adapted for #33

**Comment by guoshimin** [comment]
@alexjg Do you want to take another look at this? The package structure is now stable.

**Comment by alexjg** [comment]
Yep, happy to have another look. As far as I can see there are only two libraries missing version bounds. Now (`unordered-containers`  and `case-insensitive`). I'm not sure how much of an issue that is for packaging but if it is an issue it will require changes in https://github.com/OpenAPITools/openapi-generator/ right?

**Comment by guoshimin** [comment]
Yes, ideally.

/remove-lifecycle stale

**Pull request closed without merging**
