### PR TITLE
Add Integration tests

### LINKED ISSUE #40: Integration test on travis
https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube

### PR DESCRIPTION
**Pull request by akshaymankar**
Fixes #40 

There are two tests which can also serve as exmaples:
1. simple: reads `KUBECONFIG` from environment to create a client. Then uses the client to create a namespace and a deployment in the namespace. It then verifies if the deployment exists.
1. in-cluster: assumes it is running in a cluster and creates a namespace.

Other changes to travis config:
1. Use GHC 8.6.5 instead of 8.6.3.
1. Use lts-14 instead of 13.
1. Removed GHC 8.0.2 as it was not working after #60.
1. Run all stack builds with `--fast` for speed and also to avoid travis timeout.
1. Replace `stack --install-ghc query locals` with `stack --system-ghc query locals` in cabal builds. This removes unnecessary installation of ghc in `~/.stack`.
1. Remove all the commented out builds to reduce noise.
1. Move default stack build on top to get quicker feedback on default way of building.

My travis-foo isn't great, so I couldn't figure out how to add jobs and also keep the matrix, so I just added to the matrix. If someone has a better idea, please feel free to suggest :)

[Click here](https://travis-ci.org/akshaymankar/kubernetes-client-haskell/builds/597401976) to see the last run of the config. It is fast because most things are cached, a new PR would take much longer to run.

For all of this to be useful we should either switch on travis builds for this repository or translate this work to prow. I saw a conversation about it here: https://github.com/kubernetes/org/issues/651. I looked at prow for a bit, seems like we can get much better parallelism(much needed) and also pr tooling (arguable if we need it). But we'd definitely miss the matrix feature, caching and osx builds.

Anyhoo, I think we should enable travis builds for now and consider translating separately. From the conversation linked above I understand only members of @kubernetes-client/haskell-admins can enable travis builds. So I request one of them to please do so :)

### CODE REVIEW

**Comment by jonschoning** [comment]
FYI, there is nothing wrong with ghc-8.0.2 .

 It is with a bug introduced in `time >= 1.9.1`  
https://github.com/haskell/time/issues/119

lts-4.7 is not on time-1.9.1 yet, so that's why we haven't seen the error in stack builds.

**Comment by akshaymankar** [comment]
I am sorry this got stuck in the whole conversation about travis/prow. I think we should just merge the pull request and look at the prow separately.

/remove-lifecycle stale

**Pull request merged**
