### PR TITLE
Add custom types IntOrString and Quantity

### PR DESCRIPTION
**Pull request by jonschoning**
- regen with import-mappings
- add CustomTypes and CustomInstances
- update openapi-generator commit

Instead of A.Value, IntOrString becomes a sum type with constructors IntOrStringI and IntOrStringS
Instead of Text, Quantity becomes a newtype over Text. Currently no custom construction or serialization is implemeneted (i.e. the Text should be the wire format)
  See CustomTypes.hs for details on the Quantity type.

### CODE REVIEW

**Comment by jonschoning** [comment]
#39

**Comment by guoshimin** [comment]
Thanks for doing it! Testing it here: https://travis-ci.org/guoshimin/kubernetes-client-haskell/builds/513184702

**Pull request merged**
