### PR TITLE
Fix #56 datetime not working

### LINKED ISSUE #56: Error with DateTime Format
When trying to create a a resource with DateTime field, kubernetes returns 400 with the following message:
```
[2019-09-29 14:27:11][Kubernetes.OpenAPI.Client][Info][manjaro-v01][PID 31826][ThreadId 11] REQ:POST 192.168.99.100/apis/coordination.k8s.io/v1/namespaces/default/leases
Left (MimeError {mimeError = "error statusCode: 400", mimeErrorResponse = Response {responseStatus = Status {statusCode = 400, statusMessage = "Bad Request"}, responseVersion = HTTP/1.1, responseHeaders = [("Content-Type","application/json"),("Date","Sun, 29 Sep 2019 14:27:11 GMT"),("Content-Length","562")], responseBody = "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Lease in version \\\"v1\\\" cannot be handled as a Lease: v1.Lease.Spec: v1.LeaseSpec.HolderIdentity: AcquireTime: unmarshalerDecoder: parsing time \\\"2019-09-29T14:27:11.738Z\\\" as \\\"2006-01-02T15:04:05.000000Z07:00\\\": cannot parse \\\".738Z\\\" as \\\".000000\\\", error found in #10 byte of ...|7:11.738Z\\\",\\\"holderId|..., bigger context ...|itions\\\":1,\\\"acquireTime\\\":\\\"2019-09-29T14:27:11.738Z\\\",\\\"holderIdentity\\\":\\\"test_identity\\\",\\\"renewTime\\\":\\\"201|...\",\"reason\":\"BadRequest\",\"code\":400}\n", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}})
[2019-09-29 14:27:11][Kubernetes.OpenAPI.Client][Info][manjaro-v01][PID 31826][ThreadId 11] RES:statusCode=400 (POST 192.168.99.100/apis/coordination.k8s.io/v1/namespaces/default/leases)
[2019-09-29 14:27:11][Kubernetes.OpenAPI.Client][Error][manjaro-v01][PID 31826][ThreadId 11] error statusCode: 400
```

## Example code to reproduce:
```
{-# LANGUAGE OverloadedStrings #-}
-- module Main where

import           Data.Function                 ((&))
import           Kubernetes.Client           
import           Kubernetes.OpenAPI           
import Kubernetes.OpenAPI.API.CoordinationV1
import qualified Kubernetes.OpenAPI.API.CoreV1 as CoreV1
import           Network.TLS                   (credentialLoadX509)

import Kubernetes.OpenAPI.Model as M
import Data.Time.Clock (getCurrentTime)
import Control.Monad (forever)
import Control.Concurrent (threadDelay)
import System.Environment (getArgs, getEnv)
import Data.Text (pack)

main :: IO ()
main = do
    kcfg0 <-
        newConfig
        & fmap (setMasterURI "https://192.168.99.100:8443")
        & fmap disableValidateAuthMethods
    logContext <- stdoutLoggingContext $ configLogContext kcfg0
    let kcfg = kcfg0 { configLogContext = logContext}
    home <- getEnv "HOME"
    myCAStore <- loadPEMCerts $ home ++ "/.minikube/ca.crt"
    myCert <-
        credentialLoadX509 (home ++ "/.minikube/client.crt") (home ++ "/.minikube/client.key")
            >>= either error return
    tlsParams <-
        defaultTLSClientParams
        & fmap disableServerNameValidation
        & fmap disableServerCertValidation
        & fmap (setCAStore myCAStore)
        & fmap (setClientCert myCert)
    manager <- newManager tlsParams

    -- Create new lease
    acquireTime <- getCurrentTime
    result <- dispatchMime' manager kcfg $ createNamespacedLease (ContentType MimeJSON) (Accept MimeJSON) (newLease acquireTime) (Namespace "default")
    print result

    where
      newLease acquireTime = 
        mkV1Lease
          { v1LeaseMetadata = Just $ mkV1ObjectMeta 
            { v1ObjectMetaName = Just $ "testing"
            , v1ObjectMetaNamespace = Just $ "default"
            }
          , v1LeaseSpec = Just $ mkV1LeaseSpec
            { v1LeaseSpecAcquireTime = Just $ DateTime acquireTime
            , v1LeaseSpecHolderIdentity = Just $ "test_identity"
            , v1LeaseSpecLeaseDurationSeconds = Just $ 10
            , v1LeaseSpecRenewTime = Just $ DateTime acquireTime
            , v1LeaseSpecLeaseTransitions = Just 1
            }
          }
```

### PR DESCRIPTION
**Pull request by frincon**
This change the function to use when sending datetime fields, which solves the problem from issue #56

### CODE REVIEW

**Comment by akshaymankar** [comment]
Looks like this change is in generated a file. Maybe it should first be fixed [here in the generator first](https://github.com/OpenAPITools/openapi-generator/blob/c8d5701089a64c902d5fd1128d27883dbab7cbbf/modules/openapi-generator/src/main/resources/haskell-http-client/Core.mustache#L434-L438).

**Comment by jonschoning** [comment]
Could you try setting the codegen parameter `dateTimeFormat` to `%FT%T%QZ` and see if that works?

> formatISO8601Millis t
`2019-09-29T19:35:39.649Z`
> formatISO8601Micros t
`2019-09-29T19:35:39.649546Z`
> formatTime defaultTimeLocale "%FT%T%QZ" t
`2019-09-29T19:35:39.649546716Z`

see https://github.com/OpenAPITools/openapi-generator/tree/master/samples/client/petstore/haskell-http-client#codegen-additional-properties-parameters

**Comment by guoshimin** [comment]
@frincon Thanks for the fix. Here's where you would add the config option as @jonschoning suggested: https://github.com/kubernetes-client/gen/blob/475ad6f8e36af2b5aae7efecc75ab0b29331ee2f/openapi/haskell-http-client.xml#L34

**Comment by jonschoning** [comment]
ok so also we could do the `sed` technique as described in https://github.com/kubernetes-client/gen/pull/127 . I just didn't see it before.

**Comment by jonschoning** [comment]
@guoshimin the problem is I'm not sure if kubernetes accepts 9 decimals with %FT%T%QZ . 

If Kubernetes really only wants exactly 6 decimals, then there is no format string i believe can produce that, and so either the `sed` technique in `gen` (or just updating the upstream generator) is required.

**Comment by guoshimin** [comment]
Oh, the `sed` technique works for me!

**Comment by frincon** [comment]
@guoshimin @jonschoning I found that we can use the specified parameter `dateTimeFormat` using the format `%FT%T%6QZ`. I created the PR https://github.com/kubernetes-client/gen/pull/128 for reverting the sed and use the format parameter. I changed here the part of the code that is generated using the generator.

Sorry for the delay, I did not know the parameter before.

**Comment by frincon** [comment]
Ok, so looks like there is a bug in the template: https://github.com/OpenAPITools/openapi-generator/blob/c8d5701089a64c902d5fd1128d27883dbab7cbbf/modules/openapi-generator/src/main/resources/haskell-http-client/Core.mustache#L429

The trailing comma in the constraint... I will make another PR in the openapi generator, until then I fixed manually in this pr (https://github.com/kubernetes-client/haskell/pull/57/commits/f179218e85a47dd0e348abff076b1e95747a894f)

**Comment by jonschoning** [comment]
Thanks for finding the bug,

Maybe we should just leave the `sed` substitution in place for now then since it works fine, to avoid churn.

**Comment by frincon** [comment]
Ok, closed the PR in gen for now, and here reverted to the sed result.

**Comment by jonschoning** [comment]
I think your merge lost the dependency update to `kubernetes-client-core ==0.1.0.2`,
https://github.com/kubernetes-client/haskell/pull/57/commits/032dc2996b7b5c65dbdf1300d9d4b9666f6328d4#diff-925749c7eaf3f010ebb84d719492ee82L51
 since your're changing the version in kubernetes/kubernetes-client-core.cabal

**Comment by jonschoning** [comment]
- kubernetes-client-core > Test suite tests passed
- kubernetes-client > Test suite spec passed

(normally changes to `kubernetes-client-core` be should be made by re-running codegen; in this case the corresponding changes to codegen have also been made in https://github.com/kubernetes-client/gen)

/lgtm
/approve

**Pull request merged**
