### PR TITLE
add TokenFileAuth which reloads token after expiry

### LINKED ISSUE #54: client should periodically reload InClusterConfig token
See https://github.com/kubernetes/kubernetes/issues/70679

### PR DESCRIPTION
**Pull request by zshihang**
fixes #54. by default, this will set an expiration period of 1 minutes on service account token. as we are graduating the Beta feature Projected Service Account Volume to GA, we expect clients to reload token before it expires.

### CODE REVIEW

**Comment by zshihang** [comment]
gently ping. PTAL

**Comment by guoshimin** [comment]
@zshihang Sorry for not getting to it sooner. I have to confess that my enthusiasm for this project waned a lot after not getting needed support to enable travis CI after repeated attempts.

As for the PR, there are a lot of format changes. Can you call out the parts with actual code change so I can focus on those parts first?

Also, @akshaymankar would you mind taking a look if you have time? Some of the code that was touched in this PR was originally authored by you.

**Comment by zshihang** [comment]
thanks for the review.  

the 1 minute refresh period is explained here https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/Authentication/TokenFileAuth.cs#L26-L31.

the auto format fixer i used is [brittany](https://github.com/lspitzner/brittany/). please forgive my laziness to separate the format changes out as it has been approved.

**Comment by zshihang** [comment]
approved label is missing :)

**Pull request merged**
