### PR TITLE
add jonschoning as an owner

### PR DESCRIPTION
**Pull request by guoshimin**
@jonschoning let me know if it's ok with you.

### CODE REVIEW

**Comment by jonschoning** [comment]
Sure, It's OK with me—thanks!

**Comment by guoshimin** [comment]
@jkachmar can you /lgtm this?

**Comment by guoshimin** [comment]
:(

**Comment by jonschoning** [comment]
brendandburns invited me as a collaborator on the kubernetes-client/haskell repository via a github email.  Assuming he's done the same for jkachmar, I'm guessing jkachmar needs accept that email invitation first.

**Comment by guoshimin** [comment]
@jonschoning can you comment `lgtm` and see if that works?

**Pull request merged**
