### PR TITLE
append optional parameters instead of replace

### LINKED ISSUE #76: Issue with (-&-) optional argument operator and Command optional argument for exec
In the Exec entry point

Command has to be supplied multiple times in the query string in order to pass parameters
```
(CoreV1.connectGetNamespacedPodExec (Accept MimeAny) name namespace) -&- 
                (Command "ls") -&- 
                (Command "/") -&- 
                (Stdout True) -&- 
                (Stderr True)
```
should result in a query string of 
`?command=ls&command=/&stdout=true&stderr=true`

but actually results in a query string of
`?command=/&stdout=true&stderr=true`

### PR DESCRIPTION
**Pull request by jonschoning**

### CODE REVIEW

**Comment by jonschoning** [comment]
/retitle append optional parameters instead of replace

**Comment by jonschoning** [comment]
> Please also update the constraint in [the kubernetes-client package](https://github.com/kubernetes-client/haskell/blob/060c6f85371b1ffcf326d811c4232e473d0a86bf/kubernetes-client/package.yaml#L52) to match the new version of `kubernetes-client-core` and bump the 4th part of the version.

I thought I have done there here? 
https://github.com/kubernetes-client/haskell/pull/79/files#diff-c9d8386ac480b4b43dbdfce857fef97fe94d79c38e57a48b03a3ffc3a81c44adR52

**Review by akshaymankar — APPROVED** [review]
Whoops, I missed it in the noise.
/lgtm

**Comment by akshaymankar** [comment]
I published both packages on hackage:
https://hackage.haskell.org/package/kubernetes-client-core-0.3.1.0
https://hackage.haskell.org/package/kubernetes-client-0.3.1.0

**Pull request merged**
