### PR TITLE
new package name and module base for generated code

### PR DESCRIPTION
**Pull request by guoshimin**
New package name: kubernetes-openapi
New module base: Kubernetes.OpenAPI

Generated using https://github.com/kubernetes-client/gen/pull/105/commits/8237ccb0f7e4cc29da449d43cceac2aea9b2c4a2

On my system I had to run the command under sudo:
```
sudo ${GEN_REPO_BASE}/openapi/haskell.sh kubernetes settings
```

### CODE REVIEW

**Comment by guoshimin** [comment]
@denibertovic can you review this PR? Thanks!

**Comment by jkachmar** [comment]
Is there anything that can be done to help with this? I'm interested in using this library, and it'd be nice to have some of the moving parts get settled before it gets pushed to Hackage.

**Comment by guoshimin** [comment]
You can review this PR :)

**Comment by jkachmar** [comment]
Okay, so I did a _brief_ review of the changes (since this nearly all generated code), as well as having run this locally.

This seems like a good update, however there are two things that concern me in general:
1) the divergence between the `haskell-http-client` [swagger-codegen](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/haskell-http-client) and [openapi-generator](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/haskell-http-client) modules
2) support for newer Kubernetes APIs beyond v1.9

Parts of (1) discussed in #28; unfortunately I can't seem to get the `openapi-generator` to run successfully, so I'm not sure how to proceed here. So long as this library is locked to `swagger-codegen` it is unable to support newer Stackage snapshots and/or updated library versions, which will definitely be problematic (if it isn't already).

I'm unsure what the best way to approach (2) is; is the Kubernetes API backwards compatible between minor versions (e.g. `v1.9` -> `v1.11`)? If so, then this project should probably follow a similar model to the [python client's compatibility matrix](https://github.com/kubernetes-client/python#compatibility-matrix).

**Comment by guoshimin** [comment]
@jkachmar Thanks for taking a look!

For openapi-generator, I think we need to wait for https://github.com/kubernetes-client/gen/issues/93 to be resolved. I took a look a while ago, and it didn't seem easy to switch to openapi-genenrator just for haskell.

For 2) I think we should absolutely generate code for a more recent API version. Didn't do it here because I didn't want the two changes to be mixed together.

**Comment by jonschoning** [comment]
It looks like https://github.com/kubernetes-client/gen/pull/95 was already merged to switch python-asyncio, but we need to understand the cause of the previously linked build errors first.

**Comment by jkachmar** [comment]
@jonschoning I think that might have been my error; I was using an old commit hash for `openapi-generator`, and it may have been missing some updates.

I'm _trying_ to rerun all this now, but I'm unfortunately running into this when trying to build the `Dockerfile`:

<details><summary>Log Snippet</summary>
<p>

```
Err:6 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Packages
  Writing more data than expected (38208 > 37999)
  Hashes of expected file:
   - Filesize:37999 [weak]
   - SHA512:194ded11a350aab88b7fc1c5fee5dd6746a6bd0136ee96ad2290fc9459086daf75fbeda376ab00c0455cbeab6e64fa405f82ef0991b28322f29f30dab2aaaede
   - SHA256:369f15b8a43c29e6adf6db3329576366123c6bb749ee311f5099752de06474ea
   - SHA1:87f67045f0db46ee582998ba1d432b47900f5992 [weak]
   - MD5Sum:38eeded94abf10a911e570233047151b [weak]
  Release file created at: Tue, 19 Feb 2019 18:30:09 +0000
Fetched 3232 B in 0s (6361 B/s)                          
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  Writing more data than expected (38208 > 37999)
   Hashes of expected file:
    - Filesize:37999 [weak]
    - SHA512:194ded11a350aab88b7fc1c5fee5dd6746a6bd0136ee96ad2290fc9459086daf75fbeda376ab00c0455cbeab6e64fa405f82ef0991b28322f29f30dab2aaaede
    - SHA256:369f15b8a43c29e6adf6db3329576366123c6bb749ee311f5099752de06474ea
    - SHA1:87f67045f0db46ee582998ba1d432b47900f5992 [weak]
    - MD5Sum:38eeded94abf10a911e570233047151b [weak]
   Release file created at: Tue, 19 Feb 2019 18:30:09 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

</p>
</details>

**Comment by jonschoning** [comment]
`kubernetes-client-helper` and `kubernetes-watch` libraries would also need to be updated to depend on the new package name and module base.  

Perhaps they need to be renamed e.g. `kubernetes-openapi-client-helper` & `kubernetes-openapi-watch`

**Comment by jkachmar** [comment]
Agh, you're right I didn't even think to look in either of those modules, they'd break with the new naming scheme for sure 😞 

---

Regarding packaging, [this comment](https://github.com/kubernetes-client/haskell/pull/27#issuecomment-459062870) seems to lay out a fairly good structure.

Assuming I'm interpreting it correctly:
- `kubernetes-openapi-client-core` / `kubernetes-openapi-client-gen`
  - this would contain the generated code
- `kubernetes-openapi-client`
  - this would subsume the `kubeconfig`, `kubernetes-openapi-client-helper` and `kubernetes-openapi-watch`, as well as include/re-export the generated code

This way if someone wants to use _just_ the bindings, they're capable of doing so, but for _most_ people the happy path of a batteries included Kubernetes client is easily accessible.

**Comment by jonschoning** [comment]
That is a bit more structured and uses different package names than what guoshimin proposed, and isn't what is in this PR currently, but I do like the ergonomics of it better.

Re-exporting the codegen under a single package definitely would make discoverability much easier, than having know there are several related-but-differently-named packages that need to be used together.

**Comment by guoshimin** [comment]
@jkachmar Your proposal is better. I'll change this PR to do that!

**Comment by guoshimin** [comment]
PTAL

**Comment by jkachmar** [comment]
Looks good! 

I suppose it makes the most sense to merge this PR, then restructure the module hierarchy?

After that, if we can reconcile with the new `openapi-generator`, then it will (hopefully) be somewhat straightforward to cut an updated release and pubsish to Hackage.

**Comment by guoshimin** [comment]
What do you mean by restructure the module hierarchy? I will combine the other packages into a single one, is there something else?

**Comment by jkachmar** [comment]
What I meant by [this comment](https://github.com/kubernetes-client/haskell/pull/31#issuecomment-467490785) was that it might be more ergonomic to have a single package for the generated code (i.e. `kubernetes-openapi-client-gen`), and a single package that contains all the functionality of the `kubeconfig`, `-watch`, and `-client-helper` packages (i.e. `kubernetes-openapi-client`).

Rather than containing/publishing four separate packages, this repository could contain two:
- the `-gen` module itself
- the `-client` module, which provides a nice entry point for all the helper functionality that's built around `-gen`

Does this make sense?

**Comment by guoshimin** [comment]
Yeah, sounds good!

**Pull request merged**
