### PR TITLE
fix Incorrectly generated query strings (that rely on + not being urlencoded)

### PR DESCRIPTION
**Pull request by jonschoning**
In the Kubernetes API client, we should be able to generate queries like
    ?labelSelector=environment+in+%28production%2Cqa%29%2Ctier+in+%28frontend%29
    (from https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering).
    When the generated URIs URL-encode the plus signs, the API server rejects them.

    With this change, (newConfig :: IO KubernetesClientConfig) now sets
    the default configQueryExtraUnreserved setting to "+". Requests
    generated with this config object will avoid URI encoding "+" all
    querystring params.

### CODE REVIEW

**Comment by jonschoning** [comment]
c.f. https://github.com/kubernetes-client/haskell/issues/67

**Review by akshaymankar — APPROVED** [review]
/approve

**Pull request merged**
