### PR TITLE
Support all Kubernetes versions 1.20 through 1.30

### PR DESCRIPTION
**Pull request by thomasjm**
I noticed that when trying to use certain Kubernetes endpoints with this library (such as DELETE of a `Service`), the response would fail to parse.

Looking into it, I found it's because `kubernetes-client-core` is currently generated against K8S release 1.20, which is rather old at this point. The K8S API is pretty stable, but not stable enough that such an old version will work flawlessly against a newer cluster (mine is 1.27).

So, I decided to generate `kubernetes-client-core` for all versions from 1.20 through 1.30. These are now stored in the folders `./kubernetes-1.xx`. I think it would be nice to publish all of these to [Hackage](https://hackage.haskell.org/package/kubernetes-client-core) using their version numbers, but for now it's easy to use in a `stack.yaml` like this:

```yaml
# stack.yaml
# ...

extra-deps:
# For a project targeting Kubernetes 1.27
- git: https://github.com/codedownio/kubernetes-client-haskell.git
  commit: 47d88d7061cda5227c8f7819e3a640c7dea247f3
  subdirs:
  - kubernetes-1.27
  - kubernetes-client
```

I also:

* Made it easier and more reproducible to run the generation code, by introducing a Nix flake. You can run `generate_all.sh` and it will generate all the versions, using Nix to obtain a pinned version of the `gen` repo. This step formerly needed to be done by hand. Adding a new K8S version in the future should be a 1-line change.
* Updated the CI to run a big build matrix, testing Cabal and Stack, a range of GHC versions, and a range of K8S API versions. This CI is fully [green](https://github.com/codedownio/kubernetes-client-haskell/actions/runs/9590867803).
* Fixed all GHC warnings for the configurations in the build matrix (except for a few in the generated code).
* Moved superfluous files like `swagger.json` and `openapi.yaml` to `.gitignore`, as these are only needed at generation time and not to use the library.

I think the results are good. You can now easily choose the version of the K8S API you want to target. And a git clone is still plenty fast, with each autogenerated folder only contributing around 6MB uncompressed.

CC @jonschoning @akshaymankar @guoshimin

### CODE REVIEW

**Comment by fuadimanov** [comment]
Is anyone going to merge this?

**Comment by thomasjm** [comment]
I'm thinking about just publishing it on Hackage myself.

**Review by jonschoning — APPROVED** [review]

**Comment by jonschoning** [comment]
> I'm thinking about just publishing it on Hackage myself.

I don't have access to the hackage repo, I think that's @akshaymankar

**Pull request merged**
