### PR TITLE
update to Kubernetes 1.15 (#53)

### PR DESCRIPTION
**Pull request by jonschoning**
- update to Kubernetes 1.15 (#59)
- uses latest openapi-generator commit (https://github.com/kubernetes-client/gen/commit/8b15007940be13ce3759a1844b6015c7bfc5b4ad)
  - updates stack resolver `lts-13.9 -> lts-14.7`
  - uses custom format strings for `_readDateTime`, `_showDateTime`

### CODE REVIEW

**Comment by jonschoning** [comment]
ref https://github.com/kubernetes-client/haskell/issues/53

**Comment by akshaymankar** [comment]
Now that 1.16 is out, should we directly upgrade to 1.16?

**Comment by jonschoning** [comment]
i guess we could just do that - i'll close this PR then

**Pull request closed without merging**
