### PR TITLE
use dl.k8s.io, not kubernetes-release bucket

### PR DESCRIPTION
**Pull request by rjsadow**
This commit updates the .travis.yml file to use the updated URLs for
installing Kubernetes tools. Specifically, it modifies the installation
command for kubectl. The new URL is as follows:

https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl

This URL ensure that the latest versions of kubectl and kind are downloaded
and installed in the Travis CI environment.

#### What type of PR is this?
/kind cleanup
/kind deprecation

#### What this PR does / why we need it:
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/

dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket

ref: https://github.com/kubernetes/k8s.io/issues/2396

Signed-off-by: Ricky Sadowski <richard.j.sadowski@gmail.com>

### CODE REVIEW

**Review by Namanl2001 — APPROVED** [review]
/lgtm
Thanks!

**Comment by dims** [comment]
@brendandburns looks like unit tests are busted :(

/assign @brendandburns

**Comment by rjsadow** [comment]
@brendandburns, @guoshimin, @jkachmar, @jonschoning, @akshaymankar, can I get a review on this, please?

**Comment by akshaymankar** [comment]
The travis job doesn't exist. I would suggest let's delete the file.

**Comment by rjsadow** [comment]
@akshaymankar awesome, thanks. I'll update the pr.

**Pull request merged**
