### PR TITLE
make akshaymankar an owner

### PR DESCRIPTION
**Pull request by guoshimin**
@akshaymankar I hope this is OK with you.

### CODE REVIEW

**Comment by akshaymankar** [comment]
@guoshimin I am happy to be an owner! Thanks for adding me :)

**Comment by akshaymankar** [comment]
@guoshimin Does somebody need to add me to the org?

**Comment by jonschoning** [comment]
I guess now there as to be an issue added on https://github.com/kubernetes/org/issues per https://github.com/kubernetes/community/blob/master/community-membership.md#member to add one as a member first

**Comment by akshaymankar** [comment]
Thanks! 
It says I will need two sponsors. I guess @guoshimin is one. Would you mind being the second one @jonschoning?

**Comment by jonschoning** [comment]
sure

**Comment by akshaymankar** [comment]
Created this: https://github.com/kubernetes/org/issues/1270

**Pull request merged**
