### PR TITLE
regen for kubernetes release-1.20

### PR DESCRIPTION
**Pull request by jonschoning**

### CODE REVIEW

**Comment by jonschoning** [comment]
c.f. https://github.com/kubernetes-client/haskell/issues/86

**Comment by thomasjm** [comment]
Builds and works for me so far! Thanks for the fast turnaround.

I'd love if the Kubernetes version this is generated against were clearly advertised somehow. Just a thought, what about bumping the version number to something like `20.0.0.0`? The idea would be to put the K8S minor version as the first number and reserve the remaining three numbers for iterations of this library (so that both major and minor bumps of the client are still possible in accordance with  PVP). Assuming K8S 2.0 never comes out :)

**Comment by jonschoning** [comment]
Might be a good idea; I think first we should review how the other projects are doing versioning if we can learn something about the way they are doing it.

**Review by akshaymankar — APPROVED** [review]
/lgtm

**Pull request merged**
